

PageSize: 10

    
Elastic:
  #host: 172.17.0.2
  host: 192.168.79.177
  port: 9200
  username:
  password:

Elastic2:
  #host: 172.17.0.2
  host: 192.168.79.178
  port: 9200
  username:
  password: